import Head from 'next/head'
import Link from 'next/link'
import { ChangeEvent, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'


export default function Home() {
  const [userName, setuserName]=useState('')
  const [password, setpassword] = useState('')
  const [data, setdata] = useState([]);
  const[ message,setMessage]=useState('');
  const[path,setpath]=useState('/');

  useEffect( () => {
    fetch( `http://localhost:3000/api/getUser` )
      .then( ( res ) => { return res.json() } )
      .then( ( data ) => setdata( data ) )

  }, [] )
const HandleSUbmit=(e)=>{
 // console.log("click")
  // if (userName !== data.slug && userName !== '' && password !== ''){
  //   setMessage("UserName or password is incorrect")
  // }
  // else
   if(userName===''){
setMessage("Enter Username")
  }
  else if (password === '') {
    setMessage("Enter password")
  }
  else{
    setpath(`User / ${ userName }`)
  }
}
  return (
    <div className={` ${styles.container}`}>
      <Head>
        <title>My Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>

        <div className={styles.card}>
          <h2>Instagram</h2>
          <div className={styles.form}>
            <span>{message}</span>
            <div>
              <input type='text' name='username' placeholder='username' onChange={( e ) => setuserName( e.target.value)} required></input>
            </div>
            <div>

              <input type='text' name='username' placeholder='password' onChange={ (e) => setpassword(e.target.value) } required></input>
            </div>
            <div><Link href={ `User/${ userName }`}><button onClick={ HandleSUbmit }>Submit</button></Link></div>
          </div>

        </div>

      </main>


    </div>
  )
}
